function on_project_opened(data)
  local root_path = data and data.rootPath or "unknown"
  tina.log.info("Project opened: " .. root_path)
  tina.ui.showMessage("Project opened: " .. root_path)
  if tina.panels ~= nil and type(tina.panels.setContent) == "function" then
    tina.panels.setContent("status", "Project opened: " .. root_path)
  end
end

function on_custom(data)
  local message = data and data.message or "custom event"
  if tina.panels ~= nil and type(tina.panels.appendContent) == "function" then
    tina.panels.appendContent("status", "\n" .. tostring(message))
  end
end

function on_editor_saved(data)
  local file_name = data and data.fileName or "unknown"
  tina.log.info("Editor saved: " .. file_name)
end

function on_editor_opened(data)
  local file_name = data and data.fileName or "unknown"
  tina.log.info("Editor opened: " .. file_name)
end

function on_editor_active_changed(data)
  local file_name = data and data.fileName or "unknown"
  tina.log.info("Active editor changed: " .. file_name)
  log_active_editor_snapshot()
end

function on_file_created(data)
  local path = data and data.filePath or "unknown"
  tina.log.info("File created: " .. path)
end

function on_file_renamed(data)
  local old_path = data and data.oldPath or "unknown"
  local new_path = data and data.newPath or "unknown"
  tina.log.info("File renamed: " .. old_path .. " -> " .. new_path)
end

function on_selection_changed(data)
  if data and data.hasSelection and data.selection then
    tina.log.info("Selection changed, length=" .. string.len(data.selection.text or ""))
  end
end

function on_dirty_changed(data)
  local file_name = data and data.fileName or "unknown"
  local dirty = data and data.isDirty and "dirty" or "clean"
  tina.log.info("Dirty changed: " .. file_name .. " -> " .. dirty)
end

function on_diagnostics_changed(data)
  local errors = data and data.errorCount or 0
  local warnings = data and data.warningCount or 0
  tina.log.info("Diagnostics changed: errors=" .. errors .. ", warnings=" .. warnings)

  local snapshot, err = tina.diagnostics.get()
  if snapshot == nil then
    tina.log.warn("Diagnostics snapshot unavailable: " .. tostring(err))
    return
  end
  tina.log.info("Diagnostics snapshot total=" .. tostring(snapshot.totalCount or 0))
end

local function log_workspace_snapshot()
  local files, err = tina.workspace.findFiles("*.lua", 5)
  if files == nil then
    tina.log.warn("Workspace scan skipped: " .. tostring(err))
    return
  end

  tina.log.info("Workspace Lua files found: " .. tostring(#files))
end

local command_ids = {
  toggle_file_tree = "com.example.{{PROJECT_NAME}}.toggleFileTree",
  insert_header = "com.example.{{PROJECT_NAME}}.insertHeader",
  wrap_selection = "com.example.{{PROJECT_NAME}}.wrapSelection"
}

function log_active_editor_snapshot()
  local editor = tina.editor.getActiveEditor()
  if editor == nil then
    tina.log.warn("Active editor snapshot unavailable")
    return nil
  end

  local cursor = editor.cursor
  local cursor_text = "unknown"
  if cursor ~= nil then
    cursor_text = tostring(cursor.line) .. ":" .. tostring(cursor.column)
  end

  tina.log.info(
    "Active editor => file=" .. tostring(editor.fileName) ..
      ", language=" .. tostring(editor.languageId) ..
      ", dirty=" .. tostring(editor.isDirty) ..
      ", cursor=" .. cursor_text
  )
  return editor
end

local function comment_prefix_for(language_id)
  if language_id == "python" or language_id == "shell" or language_id == "yaml" then
    return "#"
  end
  return "//"
end

function on_toggle_file_tree(payload)
  local target_name = payload and payload.fileName or "workspace"
  tina.log.info("Plugin command triggered for: " .. target_name)

  local ok, err = tina.commands.execute("view.toggleFileTree")
  if not ok and err ~= nil then
    tina.log.warn("Nested host command failed: " .. tostring(err))
  end
end

function on_insert_header(payload)
  local editor = log_active_editor_snapshot()
  if editor == nil then
    return
  end

  local prefix = comment_prefix_for(editor.languageId)
  local file_name = editor.fileName or "unknown"
  local header = prefix .. " Generated by {{PROJECT_NAME}} for " .. file_name .. "\n"
  local ok = tina.editor.insertText(header, 0, 0)
  if ok then
    tina.log.info("Inserted starter header into " .. file_name)
  else
    tina.log.warn("Failed to insert starter header")
  end
end

function on_wrap_selection(payload)
  local editor = log_active_editor_snapshot()
  if editor == nil then
    return
  end

  local prefix = comment_prefix_for(editor.languageId)
  local selection = tina.editor.getSelection()
  local selected_text = selection and selection.text or ""
  if selected_text ~= "" then
    local replacement = prefix .. " BEGIN\n" .. selected_text .. "\n" .. prefix .. " END"
    local ok = tina.editor.replaceSelection(replacement)
    if ok then
      tina.log.info("Wrapped selection in active editor")
    else
      tina.log.warn("replaceSelection returned false")
    end
    return
  end

  local fallback = prefix .. " TODO: plugin command ran here\n"
  local ok = tina.editor.insertText(fallback)
  if ok then
    tina.log.info("Inserted fallback text at cursor because there was no selection")
  else
    tina.log.warn("Failed to insert fallback text")
  end
end

local function register_command(command_id, callback_name, title)
  local ok, err = tina.commands.register(command_id, callback_name, title)
  if not ok and err ~= nil then
    tina.log.warn("Register command failed: " .. tostring(err))
  end
end

local language = tina.editor.getLanguage() or "unknown"
tina.log.info("Plugin loaded for language: " .. language)
tina.ui.showMessage("{{PROJECT_NAME}} loaded")
tina.events.on("project.opened", "on_project_opened")
tina.events.on("editor.opened", "on_editor_opened")
tina.events.on("editor.activeChanged", "on_editor_active_changed")
tina.events.on("editor.selectionChanged", "on_selection_changed")
tina.events.on("editor.dirtyChanged", "on_dirty_changed")
tina.events.on("editor.saved", "on_editor_saved")
tina.events.on("file.created", "on_file_created")
tina.events.on("file.renamed", "on_file_renamed")
tina.events.on("diagnostics.changed", "on_diagnostics_changed")
tina.events.on("custom", "on_custom")
if tina.panels ~= nil and type(tina.panels.setContent) == "function" then
  tina.panels.setContent("status", "{{PROJECT_NAME}} loaded")
end
if tina.events ~= nil and type(tina.events.emit) == "function" then
  tina.events.emit("custom", { message = "Custom event delivered" })
end
log_workspace_snapshot()
log_active_editor_snapshot()

register_command(command_ids.toggle_file_tree, "on_toggle_file_tree", "Toggle File Tree")
register_command(command_ids.insert_header, "on_insert_header", "Insert Starter Header")
register_command(command_ids.wrap_selection, "on_wrap_selection", "Wrap Selection")
